[package]
name = "rfetch"
version = "0.1.0"
authors = ["yi <rs@neb.best>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gethostname = "0.2.1"
sys-info = "0.7.0"